# Generated by Django 3.1.2 on 2022-10-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201012_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('user_name', models.CharField(max_length=30, verbose_name='username')),
            ],
        ),
    ]
