# Generated by Django 3.1.2 on 2022-10-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_total',
            field=models.IntegerField(default=0, verbose_name='总局数'),
        ),
    ]
