# Generated by Django 3.1.2 on 2022-10-23 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20221023_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user_total',
        ),
    ]
