# Generated by Django 3.1.2 on 2022-10-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_userdata_user_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_total',
            field=models.CharField(default='', max_length=10000, verbose_name='userdata'),
        ),
    ]
